---
name: run bamboo

# yamllint disable-line rule:truthy
on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: test-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}
  cancel-in-progress: true

permissions: {}

jobs:
  run-bamboo:
    name: Run bamboo.sh
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-15
            bamboo-call-line:
              build-type: sstmainline_coreonly_config
              compiler-type: none
              mpi-type: none
              python-version: 3.9
          - os: macos-15
            bamboo-call-line:
              build-type: sstmainline_config_no_mpi
              compiler-type: none
              mpi-type: none
              python-version: 3.9
          - os: macos-26
            bamboo-call-line:
              build-type: sstmainline_config
              compiler-type: none
              mpi-type: none
              python-version: 3.13
          - os: macos-15
            bamboo-call-line:
              build-type: sst-hgcc_withsstcore_mac
              compiler-type: none
              mpi-type: none
              python-version: 3.13
          - os: ubuntu-24.04
            bamboo-call-line:
              build-type: sst-hgcc_withsstcore_linux
              compiler-type: none
              mpi-type: none
              python-version: 3.9
            install-llvm: true
          - os: ubuntu-24.04
            bamboo-call-line:
              build-type: sstmainline_config
              compiler-type: none
              mpi-type: none
              python-version: 3.9
          - os: ubuntu-24.04
            bamboo-call-line:
              build-type: sstmainline_coreonly_config
              compiler-type: none
              mpi-type: none
              python-version: 3.9
          - os: ubuntu-24.04
            bamboo-call-line:
              build-type: sstmainline_config_no_mpi
              compiler-type: none
              mpi-type: none
              python-version: 3.9
          - os: ubuntu-24.04
            bamboo-call-line:
              build-type: sstmainline_coreonly_config_no_mpi
              compiler-type: none
              mpi-type: none
              python-version: 3.9
          - os: ubuntu-24.04
            bamboo-call-line:
              build-type: sstmainline_config_make_dist_test
              compiler-type: none
              mpi-type: none
              python-version: 3.9
          - os: ubuntu-24.04
            bamboo-call-line:
              build-type: sstmainline_config_core_make_dist_test
              compiler-type: none
              mpi-type: none
              python-version: 3.9
              # Not available yet
              #
              # - os: ubuntu-26.04
              #   bamboo-call-line:
              #     build-type: sstmainline_config
              #     compiler-type: none
              #     mpi-type: none
              #     python-version: 3.9
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
        with:
          persist-credentials: false
      - name: install system-level dependencies
        env:
          SST_INSTALL_LLVM: ${{ matrix.install-llvm == true && '1' || '0' }}
        run: |
          bash ./.github/scripts/install_os_level_dependencies.sh
      - name: Pin Python version
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          python-version: ${{ matrix.bamboo-call-line.python-version }}
      - name: ccache
        uses: hendrikmuhs/ccache-action@d62db5f07c26379fc4b4e0916f098a92573c3b03  # v1.2.23
        with:
          append-timestamp: false
          create-symlink: true
          key: >-
            ccache-${{ matrix.os }}-${{ matrix.bamboo-call-line.build-type }}-${{
            matrix.bamboo-call-line.mpi-type }}-${{ matrix.bamboo-call-line.compiler-type
            }}
          max-size: "4GB"
          verbose: 2
      - name: Clone Spack
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
        with:
          persist-credentials: false
          # Take the latest (develop) version.
          repository: spack/spack
          ref: develop
          path: spack
      - name: Add Spack to PATH
        run: |
          echo "${PWD}/spack/bin" >> "${GITHUB_PATH}"
          # echo "mirror_name=github-container-registry" >> "${GITHUB_ENV}"
      - name: Find compilers for Spack
        run: |
          spack compiler find
          spack config blame config
          spack debug report
      - name: try module stuff
        shell: /bin/bash -el {0}
        run: |
          module avail
      - name: set env and prepare dir structure
        run: |
          # Keep this common in order to increase ccache effectiveness
          # sst_deps_user_dir="${GITHUB_WORKSPACE}/../${GITHUB_RUN_ID}_${GITHUB_RUN_NUMBER}_${GITHUB_RUN_ATTEMPT}"
          sst_deps_user_dir="${GITHUB_WORKSPACE}/../sst-deps-user-dir"
          mkdir -p "${sst_deps_user_dir}"
          SST_DEPS_USER_DIR="$(realpath "${sst_deps_user_dir}")"
          echo "SST_DEPS_USER_DIR=${SST_DEPS_USER_DIR}" >> "${GITHUB_ENV}"
          echo "SST_DEPS_TREE=${SST_DEPS_USER_DIR}/devel" >> "${GITHUB_ENV}"
      - name: fetch elements dependencies
        run: |
          pristine="${SST_DEPS_USER_DIR}"/sstDeps/src/pristine
          mkdir -p "${pristine}"
          cd "${pristine}"
          wget https://github.com/umd-memsys/DRAMSim2/archive/refs/tags/v2.2.2.tar.gz
      - name: run bamboo
        env:
          BUILD_TYPE: ${{ matrix.bamboo-call-line.build-type }}
          COMPILER_TYPE: ${{ matrix.bamboo-call-line.compiler-type }}
          MPI_TYPE: ${{ matrix.bamboo-call-line.mpi-type }}
        run: |
          bash ./.github/scripts/call_bamboo.sh
          ccache -s -vv
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          name: >-
            test-output-${{ matrix.os }}-${{ matrix.bamboo-call-line.build-type }}-${{
            matrix.bamboo-call-line.mpi-type }}-${{ matrix.bamboo-call-line.compiler-type
            }}
          path: |
            ${{ env.SST_DEPS_TREE }}/sqe/test/testOutputs
            ${{ env.SST_DEPS_TREE }}/sqe/test/test-reports
            ${{ env.SST_DEPS_TREE }}/trunk/sst-hgcc/tests/lit-junit.xml
            ${{ env.SST_DEPS_TREE }}/trunk/sst-hgcc/tests/lit-tests/Output
            ${{ env.SST_DEPS_TREE }}/trunk/sst-hgcc-builddir/tests/lit-junit.xml
            ${{ env.SST_DEPS_TREE }}/trunk/sst-hgcc-builddir/tests/lit-tests/Output
          if-no-files-found: warn
          compression-level: 9
        if: '!cancelled()'
